In [2]:
print("Hello World!")

Hello World!


# Hello I Am Learning Maching Learning

- sets

In [15]:
set1 = set()
set1

set()

In [18]:
set1.add(3)
set1.add(4)
set1.add(2)
set1

{2, 3, 4}

In [19]:
set1.pop()

2

In [20]:
set1

{3, 4}

In [22]:
set1.remove(4)
set1

{3}

In [23]:
set1 = {2,4,2,4,2,4,22,5,5,6,5,432}
set1

{2, 4, 5, 6, 22, 432}

In [25]:
set2 = {3,2,4,5,3,2,22}
set1.difference(set2)

{6, 432}

In [30]:
str1 = "abcdh"
str2 = "abcdef"
set1 = set(str1)
set2 = set(str2)
set1,set2

({'a', 'b', 'c', 'd', 'h'}, {'a', 'b', 'c', 'd', 'e', 'f'})

In [31]:
set2.union(set1)

{'a', 'b', 'c', 'd', 'e', 'f', 'h'}

In [32]:
set1.update(set2)

In [33]:
set1

{'a', 'b', 'c', 'd', 'e', 'f', 'h'}

### Numpy

In [2]:
import numpy as np

- 1D Array

In [36]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [37]:
type(arr)

numpy.ndarray

In [38]:
print(arr)

[1 2 3 4 5]


In [39]:
arr.shape

(5,)

In [8]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [5,6,7,8,9]
my_lst3 = [5,4,6,6,5]
arr1 = np.array([my_lst1, my_lst2, my_lst3])
arr1

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [5, 4, 6, 6, 5]])

In [11]:
arr1.shape

(3, 5)

In [12]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 5],
       [6, 7, 8],
       [9, 5, 4],
       [6, 6, 5]])

- Indexing

In [15]:
arr = np.array([1,2,3,4,8,5,3,2])

In [16]:
arr[3]

4

In [17]:
arr

array([1, 2, 3, 4, 8, 5, 3, 2])

In [18]:
arr1

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [5, 4, 6, 6, 5]])

In [20]:
arr1[:,:]

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [5, 4, 6, 6, 5]])

In [21]:
arr1[0:2,:]

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [29]:
arr1[1,:]

array([5, 6, 7, 8, 9])

In [30]:
arr1[:,3:]

array([[4, 5],
       [8, 9],
       [6, 5]])

In [31]:
arr1[1:,3:]

array([[8, 9],
       [6, 5]])

In [34]:
arr1 = np.arange(0,10)

In [35]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr = np.arange(0,100,step = 5)

In [40]:
len(arr)

20

In [52]:
arr.reshape(5,4)


array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [46]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [56]:
arr[5:] = 50

In [53]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [54]:
arr1 = arr

In [55]:
arr1 = arr.copy()
arr1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [58]:
arr


array([ 0,  5, 10, 15, 20, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50])